タスク１　提出1回目
kato-reina/BudgetTracker pull request #1
Opened 2024-12-13 05:02 UTC by kato-reina

## 詳細
Main,Form,Tableの作成とOptionalに取り組みました。

## 画面キャプチャ 
初期画面(Formをデフォルト表示)
![スクリーンショット 2024-12-13 134232](https://github.com/user-attachments/assets/8ef8ef09-1033-4a36-b802-bb6e8ab9a4fa)

ボタンで切り替え(同じボタン複数回押下はそのまま)
![スクリーンショット 2024-12-13 135521](https://github.com/user-attachments/assets/a87de29e-7ad2-4e17-b8f0-cd9c9e9c337b)

2024-12-17 04:40 UTC, takumi-13 requested changes

2024-12-17 04:40 UTC, takumi-13 commented on src/App.vue
> +      <!-- <Test2 msg="Test2" /> -->
不要なコードはコメントアウトで残すのではなく、削除するようにしてください。
ノイズになり見づらくなってしまうので。

2024-12-17 04:40 UTC, takumi-13 commented on src/App.vue
> +      <!-- <Test2 msg="Test2" /> -->
他のコメントアウトの箇所も本当に必要なコメントだけ残すようにお願いします。

2024-12-17 04:40 UTC, takumi-13 commented on src/App.vue
> +      <!-- 新しく追加 -->
このコメントも不要かと思います。
理由としては、下記X点です。
- 他の修正を加えた場合、”新しく追加”が嘘になってしまう
  - その時消せばいいのでは？と思うかもだけど、だいたい消し忘れが発生して よくわらかないコメントが大量にある状態になってしまいがち
- コードに対する補足ではない
  - 今回追加したことを丁寧に明示してもらってるのだと思うけど、追加した事はGitを見ればよい
  - コメントとして残してほしいのは、原則コードに対する補足情報のみにしてほしい

2024-12-17 04:40 UTC, takumi-13 commented on src/App.vue
> +    <div class="house">
`house`って`class`あったっけ？不要なように見える

2024-12-17 04:40 UTC, takumi-13 commented on src/App.vue
> +    <div class="house">
そもそもここで`div`タグを追加する必要ないように見えます。
何か意図があれば教ええください！

2024-12-17 04:40 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +  };
1. `SwitchToForm`とPascalケースになっているので、camelケースで書くようにしてください
2. まずはpageSelectを変更する関数を用意してあげて引数として変更する値を書いてあげる方がよい。
   - 仮にPageが増えた場合、true/falseだけでは表現できなくなってしまう。
   - その場合、関数を増やしてあげなければならないので、 記述が冗長になってしまう。
   - 仮にそれぞれ関数として定義してあげたいのであれば、下記のように書くのがいいかなー
     ※ switchToForm/switchToTableを用意するまでもないと考えるのであれば、関数だけ定義してあげて、呼び出すときに何に変えたいかを記載するようにする（ここは好み） 
```
  const SELECTED_PAGE_FORM = true
  const SELECTED_PAGE_TABLE = false
  const setPageSelect = (x:Boolean) => pageSelect.value = x
  const switchToForm = setPageSelect(SELECTED_PAGE_FORM)
  const switchToTable = setPageSelect(SELECTED_PAGE_TABLE)
```

2024-12-17 04:40 UTC, takumi-13 commented on src/components/Table.vue
> +  ]);
テストデータなのでこのままでもよいのですが、配列関数の練習をして頭の体操しましょうか！
この内容をワンライナーで定義してみてください。
イメージとしては下記のような形です。
const TABLE_DATES = [X,Y,Z].map((item,index) => 要素を表現)

2024-12-17 04:40 UTC, takumi-13 commented on src/components/Table.vue
> +        <th class="py-2 px-4 bg-gray-200 text-gray-600 font-bold uppercase text-sm">row10</th>
v-for使ってもっと簡潔にかけそう！

2024-12-17 04:40 UTC, takumi-13 commented on src/components/Table.vue
> +        <td class="py-2 px-4 border-b border-gray-200">{{ row.row10 }}</td>
v-for使ってもっと簡潔にかけそう！

2024-12-17 04:40 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +      <div class="m-4">
tailwind使えてていいと思う！
ただ、l24とl32の記述が同じで冗長になっているので、変数として定義して再利用してあげたほうがいいかな！
同じものは一度書いたら二度と書かないように意識してみるといいと思う！

また、Buttonは横並びではなく、サイドバーのようなUIとしてあげてそこに置きたいかな！
イメージとしては添付画像のような感じ！
![image](https://github.com/user-attachments/assets/820040e1-9c55-4cc2-8952-e1ba26cd8d7f)

2024-12-17 06:09 UTC, nssol-takumi commented on src/components/HouseholdMain.vue
> +          @click="switchToTable"
"bg-blue-500 hover:bg-blue-400 active:bg-blue-600 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 active:border-none active:translate-y-1 rounded h-12"

"bg-green-500 hover:bg-green-400 active:bg-green-600 "


const commonStyle = "text-white font-bold py-2 px-4 border-b-4 border-green-700 hover:border-green-500 active:border-none active:translate-y-1 rounded h-12"

const greenButtonStyle = "bg-green-500" + commonStyle
const greenButtonStyle = `bg-green-500 ${commonStyle}`

2024-12-18 02:56 UTC, kato-reina commented
## 詳細
レビューでの指摘箇所を修正しました。
## 画面キャプチャ 
ボタンをサイドに配置しました。
![スクリーンショット 2024-12-18 115137](https://github.com/user-attachments/assets/656f553b-d1e7-4279-b92e-a79271d2e2ca)

2024-12-23 09:49 UTC, merged